


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."backtesting_custom_metrics" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "type" "text" DEFAULT 'checkbox'::"text",
    "active" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "backtesting_custom_metrics_type_check" CHECK (("type" = ANY (ARRAY['checkbox'::"text", 'number'::"text", 'text'::"text"])))
);


ALTER TABLE "public"."backtesting_custom_metrics" OWNER TO "postgres";


ALTER TABLE "public"."backtesting_custom_metrics" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."backtesting_custom_metrics_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."backtesting_metrics" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "metric_type" "text" DEFAULT 'checkbox'::"text" NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."backtesting_metrics" OWNER TO "postgres";


ALTER TABLE "public"."backtesting_metrics" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."backtesting_metrics_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."backtesting_sessions" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "asset" "text" NOT NULL,
    "strategy" "text",
    "account" "text",
    "start_date" "date" NOT NULL,
    "end_date" "date" NOT NULL,
    "status" "text" DEFAULT 'in_progress'::"text",
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "account_capital" numeric DEFAULT 0,
    CONSTRAINT "backtesting_sessions_status_check" CHECK (("status" = ANY (ARRAY['in_progress'::"text", 'completed'::"text", 'paused'::"text"])))
);


ALTER TABLE "public"."backtesting_sessions" OWNER TO "postgres";


ALTER TABLE "public"."backtesting_sessions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."backtesting_sessions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."backtesting_settings" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "accounts" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "strategies" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "assets" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "sessions" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "default_account" "text",
    "default_strategy" "text",
    "default_asset" "text",
    "default_risk" numeric DEFAULT 100,
    "default_rr" numeric DEFAULT 2,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."backtesting_settings" OWNER TO "postgres";


ALTER TABLE "public"."backtesting_settings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."backtesting_settings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."backtesting_trades" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "date" "date" NOT NULL,
    "asset" "text" NOT NULL,
    "strategy" "text",
    "session" "text",
    "direction" "text",
    "result" "text",
    "entry_price" numeric,
    "stop_loss" numeric,
    "take_profit" numeric,
    "risk_amount" numeric DEFAULT 0,
    "rr_planned" numeric DEFAULT 0,
    "rr_result" numeric DEFAULT 0,
    "pnl" numeric DEFAULT 0,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "session_id" bigint,
    "custom_metrics" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "be_after_result" "text",
    CONSTRAINT "backtesting_trades_be_after_result_check" CHECK ((("be_after_result" = ANY (ARRAY['TP'::"text", 'SL'::"text"])) OR ("be_after_result" IS NULL))),
    CONSTRAINT "backtesting_trades_direction_check" CHECK (("direction" = ANY (ARRAY['LONG'::"text", 'SHORT'::"text"]))),
    CONSTRAINT "backtesting_trades_result_check" CHECK (("result" = ANY (ARRAY['TP'::"text", 'SL'::"text", 'BE'::"text"])))
);


ALTER TABLE "public"."backtesting_trades" OWNER TO "postgres";


ALTER TABLE "public"."backtesting_trades" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."backtesting_trades_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."real_accounts" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid",
    "name" "text",
    "balance" numeric,
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."real_accounts" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."real_strategies" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid",
    "name" "text",
    "risk_type" "text",
    "risk_value" numeric,
    "rr" numeric,
    "notes" "text",
    "is_active" boolean DEFAULT true,
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."real_strategies" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."trades" (
    "id" bigint NOT NULL,
    "date" "text",
    "asset" "text",
    "result" "text",
    "pnl" real,
    "strategy" "text",
    "account" "text",
    "lotaje" real,
    "commission" real,
    "pnl_net" real,
    "image_before" "text",
    "image_after" "text",
    "user_id" "uuid",
    "be_after_result" "text",
    "updated_at" timestamp with time zone,
    CONSTRAINT "trades_be_after_result_check" CHECK ((("be_after_result" = ANY (ARRAY['TP'::"text", 'SL'::"text"])) OR ("be_after_result" IS NULL)))
);


ALTER TABLE "public"."trades" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."trades_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."trades_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."trades_id_seq" OWNED BY "public"."trades"."id";



ALTER TABLE ONLY "public"."trades" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."trades_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."backtesting_custom_metrics"
    ADD CONSTRAINT "backtesting_custom_metrics_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."backtesting_metrics"
    ADD CONSTRAINT "backtesting_metrics_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."backtesting_sessions"
    ADD CONSTRAINT "backtesting_sessions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."backtesting_settings"
    ADD CONSTRAINT "backtesting_settings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."backtesting_settings"
    ADD CONSTRAINT "backtesting_settings_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."backtesting_trades"
    ADD CONSTRAINT "backtesting_trades_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."real_accounts"
    ADD CONSTRAINT "real_accounts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."real_strategies"
    ADD CONSTRAINT "real_strategies_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."trades"
    ADD CONSTRAINT "trades_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."backtesting_custom_metrics"
    ADD CONSTRAINT "backtesting_custom_metrics_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."backtesting_metrics"
    ADD CONSTRAINT "backtesting_metrics_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."backtesting_sessions"
    ADD CONSTRAINT "backtesting_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."backtesting_settings"
    ADD CONSTRAINT "backtesting_settings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."backtesting_trades"
    ADD CONSTRAINT "backtesting_trades_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "public"."backtesting_sessions"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."backtesting_trades"
    ADD CONSTRAINT "backtesting_trades_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."real_accounts"
    ADD CONSTRAINT "real_accounts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."real_strategies"
    ADD CONSTRAINT "real_strategies_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Allow all inserts" ON "public"."trades" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow all select" ON "public"."trades" FOR SELECT USING (true);



CREATE POLICY "Allow insert (no auth)" ON "public"."trades" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow select own trades" ON "public"."trades" FOR SELECT USING (true);



CREATE POLICY "Users can delete own accounts" ON "public"."real_accounts" FOR DELETE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can delete own backtesting custom metrics" ON "public"."backtesting_custom_metrics" FOR DELETE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can delete own backtesting metrics" ON "public"."backtesting_metrics" FOR DELETE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can delete own backtesting sessions" ON "public"."backtesting_sessions" FOR DELETE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can delete own backtesting trades" ON "public"."backtesting_trades" FOR DELETE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can delete own strategies" ON "public"."real_strategies" FOR DELETE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can insert own accounts" ON "public"."real_accounts" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can insert own backtesting custom metrics" ON "public"."backtesting_custom_metrics" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can insert own backtesting metrics" ON "public"."backtesting_metrics" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can insert own backtesting sessions" ON "public"."backtesting_sessions" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can insert own backtesting settings" ON "public"."backtesting_settings" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can insert own backtesting trades" ON "public"."backtesting_trades" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can insert own strategies" ON "public"."real_strategies" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can see own accounts" ON "public"."real_accounts" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can see own strategies" ON "public"."real_strategies" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can update own accounts" ON "public"."real_accounts" FOR UPDATE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can update own backtesting custom metrics" ON "public"."backtesting_custom_metrics" FOR UPDATE USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can update own backtesting metrics" ON "public"."backtesting_metrics" FOR UPDATE USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can update own backtesting sessions" ON "public"."backtesting_sessions" FOR UPDATE USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can update own backtesting settings" ON "public"."backtesting_settings" FOR UPDATE USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can update own backtesting trades" ON "public"."backtesting_trades" FOR UPDATE USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can update own strategies" ON "public"."real_strategies" FOR UPDATE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can view own backtesting custom metrics" ON "public"."backtesting_custom_metrics" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can view own backtesting metrics" ON "public"."backtesting_metrics" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can view own backtesting sessions" ON "public"."backtesting_sessions" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can view own backtesting settings" ON "public"."backtesting_settings" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can view own backtesting trades" ON "public"."backtesting_trades" FOR SELECT USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."backtesting_custom_metrics" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."backtesting_metrics" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."backtesting_sessions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."backtesting_settings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."backtesting_trades" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."real_accounts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."real_strategies" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."trades" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "users_delete_own_backtesting_custom_metrics" ON "public"."backtesting_custom_metrics" FOR DELETE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "users_delete_own_backtesting_metrics" ON "public"."backtesting_metrics" FOR DELETE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "users_delete_own_backtesting_sessions" ON "public"."backtesting_sessions" FOR DELETE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "users_delete_own_backtesting_settings" ON "public"."backtesting_settings" FOR DELETE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "users_delete_own_backtesting_trades" ON "public"."backtesting_trades" FOR DELETE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "users_delete_own_trades" ON "public"."trades" FOR DELETE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "users_insert_own_backtesting_custom_metrics" ON "public"."backtesting_custom_metrics" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "users_insert_own_backtesting_metrics" ON "public"."backtesting_metrics" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "users_insert_own_backtesting_sessions" ON "public"."backtesting_sessions" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "users_insert_own_backtesting_settings" ON "public"."backtesting_settings" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "users_insert_own_backtesting_trades" ON "public"."backtesting_trades" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "users_insert_own_trades" ON "public"."trades" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "users_select_own_backtesting_custom_metrics" ON "public"."backtesting_custom_metrics" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "users_select_own_backtesting_metrics" ON "public"."backtesting_metrics" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "users_select_own_backtesting_sessions" ON "public"."backtesting_sessions" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "users_select_own_backtesting_settings" ON "public"."backtesting_settings" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "users_select_own_backtesting_trades" ON "public"."backtesting_trades" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "users_select_own_trades" ON "public"."trades" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "users_update_own_backtesting_custom_metrics" ON "public"."backtesting_custom_metrics" FOR UPDATE USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "users_update_own_backtesting_metrics" ON "public"."backtesting_metrics" FOR UPDATE USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "users_update_own_backtesting_sessions" ON "public"."backtesting_sessions" FOR UPDATE USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "users_update_own_backtesting_settings" ON "public"."backtesting_settings" FOR UPDATE USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "users_update_own_backtesting_trades" ON "public"."backtesting_trades" FOR UPDATE USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "users_update_own_trades" ON "public"."trades" FOR UPDATE USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";





































































































































































GRANT ALL ON TABLE "public"."backtesting_custom_metrics" TO "anon";
GRANT ALL ON TABLE "public"."backtesting_custom_metrics" TO "authenticated";
GRANT ALL ON TABLE "public"."backtesting_custom_metrics" TO "service_role";



GRANT ALL ON SEQUENCE "public"."backtesting_custom_metrics_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."backtesting_custom_metrics_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."backtesting_custom_metrics_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."backtesting_metrics" TO "anon";
GRANT ALL ON TABLE "public"."backtesting_metrics" TO "authenticated";
GRANT ALL ON TABLE "public"."backtesting_metrics" TO "service_role";



GRANT ALL ON SEQUENCE "public"."backtesting_metrics_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."backtesting_metrics_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."backtesting_metrics_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."backtesting_sessions" TO "anon";
GRANT ALL ON TABLE "public"."backtesting_sessions" TO "authenticated";
GRANT ALL ON TABLE "public"."backtesting_sessions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."backtesting_sessions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."backtesting_sessions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."backtesting_sessions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."backtesting_settings" TO "anon";
GRANT ALL ON TABLE "public"."backtesting_settings" TO "authenticated";
GRANT ALL ON TABLE "public"."backtesting_settings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."backtesting_settings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."backtesting_settings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."backtesting_settings_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."backtesting_trades" TO "anon";
GRANT ALL ON TABLE "public"."backtesting_trades" TO "authenticated";
GRANT ALL ON TABLE "public"."backtesting_trades" TO "service_role";



GRANT ALL ON SEQUENCE "public"."backtesting_trades_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."backtesting_trades_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."backtesting_trades_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."real_accounts" TO "anon";
GRANT ALL ON TABLE "public"."real_accounts" TO "authenticated";
GRANT ALL ON TABLE "public"."real_accounts" TO "service_role";



GRANT ALL ON TABLE "public"."real_strategies" TO "anon";
GRANT ALL ON TABLE "public"."real_strategies" TO "authenticated";
GRANT ALL ON TABLE "public"."real_strategies" TO "service_role";



GRANT ALL ON TABLE "public"."trades" TO "anon";
GRANT ALL ON TABLE "public"."trades" TO "authenticated";
GRANT ALL ON TABLE "public"."trades" TO "service_role";



GRANT ALL ON SEQUENCE "public"."trades_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."trades_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."trades_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































