-- Tabla independiente de trades reales. RLS: habilitar en Supabase y políticas por user_id.
create table if not exists public.backtesting_trades (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  date text not null default '',
  asset text not null default '',
  strategy text not null default '',
  session text not null default '',
  direction text not null default 'LONG',
  result text not null default 'BE',
  entry_price numeric not null default 0,
  stop_loss numeric not null default 0,
  take_profit numeric not null default 0,
  risk_eur numeric not null default 0,
  rr_planned numeric not null default 0,
  rr_result numeric not null default 0,
  pnl_estimated numeric not null default 0,
  notes text not null default '',
  account text not null default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists backtesting_trades_user_id_idx on public.backtesting_trades (user_id);
create index if not exists backtesting_trades_date_idx on public.backtesting_trades (user_id, date);

comment on table public.backtesting_trades is 'Operaciones de backtesting (no mezclar con trades). Habilitar RLS y políticas por user_id en Supabase.';
