-- Configuración solo backtesting (independiente de cuentas/estrategias reales)
create table if not exists public.backtesting_settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,

  accounts jsonb not null default '[]'::jsonb,
  strategies jsonb not null default '[]'::jsonb,
  assets jsonb not null default '[]'::jsonb,
  sessions jsonb not null default '[]'::jsonb,

  default_account text,
  default_strategy text,
  default_asset text,
  default_risk numeric default 100,
  default_rr numeric default 2,

  created_at timestamptz default now(),
  updated_at timestamptz default now(),

  unique (user_id)
);

alter table public.backtesting_settings enable row level security;

create policy "Users can view own backtesting settings"
on public.backtesting_settings
for select
using (auth.uid() = user_id);

create policy "Users can insert own backtesting settings"
on public.backtesting_settings
for insert
with check (auth.uid() = user_id);

create policy "Users can update own backtesting settings"
on public.backtesting_settings
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
