-- Tabla unificada public.backtesting_metrics (antes backtesting_custom_metrics en 004).
-- Idempotente: renombra si hace falta, crea si no existe ninguna, RLS alineado con la app.

do $$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'backtesting_custom_metrics'
  ) and not exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'backtesting_metrics'
  ) then
    alter table public.backtesting_custom_metrics rename to backtesting_metrics;
    if exists (
      select 1 from pg_indexes
      where schemaname = 'public' and indexname = 'backtesting_custom_metrics_user_id_idx'
    ) then
      alter index public.backtesting_custom_metrics_user_id_idx rename to backtesting_metrics_user_id_idx;
    end if;
  end if;
end $$;

create table if not exists public.backtesting_metrics (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  description text,
  metric_type text not null default 'checkbox',
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists backtesting_metrics_user_id_idx on public.backtesting_metrics (user_id);

alter table public.backtesting_metrics
  alter column description drop not null;

alter table public.backtesting_trades
  add column if not exists custom_metrics jsonb not null default '{}'::jsonb;

alter table public.backtesting_metrics enable row level security;

drop policy if exists "Users can view own backtesting custom metrics" on public.backtesting_metrics;
drop policy if exists "Users can insert own backtesting custom metrics" on public.backtesting_metrics;
drop policy if exists "Users can update own backtesting custom metrics" on public.backtesting_metrics;
drop policy if exists "Users can delete own backtesting custom metrics" on public.backtesting_metrics;

drop policy if exists "Users can view own backtesting metrics" on public.backtesting_metrics;
drop policy if exists "Users can insert own backtesting metrics" on public.backtesting_metrics;
drop policy if exists "Users can update own backtesting metrics" on public.backtesting_metrics;
drop policy if exists "Users can delete own backtesting metrics" on public.backtesting_metrics;

create policy "Users can view own backtesting metrics"
on public.backtesting_metrics for select
using (auth.uid() = user_id);

create policy "Users can insert own backtesting metrics"
on public.backtesting_metrics for insert
with check (auth.uid() = user_id);

create policy "Users can update own backtesting metrics"
on public.backtesting_metrics for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own backtesting metrics"
on public.backtesting_metrics for delete
using (auth.uid() = user_id);
