-- Sesiones de backtest (entidades independientes de trades reales)
create table if not exists public.backtesting_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null default '',
  asset text not null default '',
  strategy text not null default '',
  account text not null default '',
  start_date date,
  end_date date,
  status text not null default 'in_progress',
  notes text not null default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists backtesting_sessions_user_id_idx on public.backtesting_sessions (user_id);

comment on table public.backtesting_sessions is 'Sesiones de backtest por usuario. Habilitar RLS en Supabase.';

alter table public.backtesting_sessions enable row level security;

create policy "Users can view own backtesting sessions"
on public.backtesting_sessions for select
using (auth.uid() = user_id);

create policy "Users can insert own backtesting sessions"
on public.backtesting_sessions for insert
with check (auth.uid() = user_id);

create policy "Users can update own backtesting sessions"
on public.backtesting_sessions for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own backtesting sessions"
on public.backtesting_sessions for delete
using (auth.uid() = user_id);

-- Métricas / ticks personalizados por usuario
create table if not exists public.backtesting_custom_metrics (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null default '',
  description text not null default '',
  metric_type text not null default 'checkbox',
  is_active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists backtesting_custom_metrics_user_id_idx on public.backtesting_custom_metrics (user_id);

comment on table public.backtesting_custom_metrics is 'Métricas personalizadas para trades de backtesting. metric_type: checkbox | number | text';

alter table public.backtesting_custom_metrics enable row level security;

create policy "Users can view own backtesting custom metrics"
on public.backtesting_custom_metrics for select
using (auth.uid() = user_id);

create policy "Users can insert own backtesting custom metrics"
on public.backtesting_custom_metrics for insert
with check (auth.uid() = user_id);

create policy "Users can update own backtesting custom metrics"
on public.backtesting_custom_metrics for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own backtesting custom metrics"
on public.backtesting_custom_metrics for delete
using (auth.uid() = user_id);

-- Operaciones: enlace a sesión de backtest y métricas JSON
alter table public.backtesting_trades
  add column if not exists session_id bigint references public.backtesting_sessions (id) on delete set null;

alter table public.backtesting_trades
  add column if not exists custom_metrics jsonb not null default '{}'::jsonb;

create index if not exists backtesting_trades_session_id_idx on public.backtesting_trades (user_id, session_id);
